CREATE TABLE `magic`.`expansion` (
  `code` VARCHAR(4) NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `card_quantity` INT,
  `type` VARCHAR(20),
  `release_date` DATE NOT NULL,
  `block` VARCHAR(45),
  PRIMARY KEY (`code`, `name`),
  UNIQUE INDEX `name_code_UNIQUE` (`code` ASC, `name` ASC) INVISIBLE,
  INDEX `name_IDX` (`name` ASC) VISIBLE);

START TRANSACTION;
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('AKH','Amonkhet',264,STR_TO_DATE('04.28.2017', GET_FORMAT(DATE,'USA')),'Amonkhet Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('HOU','Hour of Devastation',184,STR_TO_DATE('07.14.2017', GET_FORMAT(DATE,'USA')),'Amonkhet Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ATQ','Antiquities',100,STR_TO_DATE('03.04.1994', GET_FORMAT(DATE,'USA')),'Antiquities');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ARN','Arabian Nights',92,STR_TO_DATE('12.17.1993', GET_FORMAT(DATE,'USA')),'Arabian Nights');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('BFZ','Battle for Zendikar',274,STR_TO_DATE('10.02.2015', GET_FORMAT(DATE,'USA')),'Battle For Zendikar Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('OGW','Oath of the Gatewatch',184,STR_TO_DATE('01.22.2016', GET_FORMAT(DATE,'USA')),'Battle For Zendikar Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('BRB','Battle Royale',136,STR_TO_DATE('11.12.1999', GET_FORMAT(DATE,'USA')),'Box Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('BTD','Beatdown',122,STR_TO_DATE('10.01.2000', GET_FORMAT(DATE,'USA')),'Box Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('CNS','Conspiracy',210,STR_TO_DATE('06.06.2014', GET_FORMAT(DATE,'USA')),'Casual supplements');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('CN2','Conspiracy: Take the Crown',221,STR_TO_DATE('08.26.2016', GET_FORMAT(DATE,'USA')),'Casual supplements');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('HOP','Planechase',null,STR_TO_DATE('09.04.2009', GET_FORMAT(DATE,'USA')),'Casual supplements');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ARC','Archenemy',null,STR_TO_DATE('06.18.2010', GET_FORMAT(DATE,'USA')),'Casual supplements');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('PC2','Planechase 2012 Edition',null,STR_TO_DATE('06.01.2012', GET_FORMAT(DATE,'USA')),'Casual supplements');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('PCA','Planechase Anthology',null,STR_TO_DATE('11.25.2016', GET_FORMAT(DATE,'USA')),'Casual supplements');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('E01','Archenemy: Nicol Bolas',260,STR_TO_DATE('06.16.2017', GET_FORMAT(DATE,'USA')),'Casual supplements');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('E02','Explorers of Ixalan',null,STR_TO_DATE('11.24.2017', GET_FORMAT(DATE,'USA')),'Casual supplements');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('CMD','Magic: The Gathering-Commander (Commander 2011)',null,STR_TO_DATE('06.17.2011', GET_FORMAT(DATE,'USA')),'Commander');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('CM1','Commander''s Arsenal',null,STR_TO_DATE('11.02.2012', GET_FORMAT(DATE,'USA')),'Commander');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('C13','Commander 2013',null,STR_TO_DATE('01.11.2013', GET_FORMAT(DATE,'USA')),'Commander');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('C14','Commander 2014',null,STR_TO_DATE('11.07.2014', GET_FORMAT(DATE,'USA')),'Commander');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('C15','Commander 2015',null,STR_TO_DATE('11.13.2015', GET_FORMAT(DATE,'USA')),'Commander');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('C16','Commander 2016',null,STR_TO_DATE('11.11.2016', GET_FORMAT(DATE,'USA')),'Commander');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('C17','Commander 2017',null,STR_TO_DATE('08.25.2017', GET_FORMAT(DATE,'USA')),'Commander');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('CMA','Commander Anthology',null,STR_TO_DATE('06.06.2017', GET_FORMAT(DATE,'USA')),'Commander');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('C18','Commander 2018',null,STR_TO_DATE('08.09.2018', GET_FORMAT(DATE,'USA')),'Commander');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('CM2','Commander Anthology 2018',null,STR_TO_DATE('06.08.2018', GET_FORMAT(DATE,'USA')),'Commander');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('2ED','Unlimited Edition',302,STR_TO_DATE('12.01.1993', GET_FORMAT(DATE,'USA')),'Core Set');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('3ED','Revised Edition',306,STR_TO_DATE('04.01.1994', GET_FORMAT(DATE,'USA')),'Core Set');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('4ED','Fourth Edition',378,STR_TO_DATE('04.01.1995', GET_FORMAT(DATE,'USA')),'Core Set');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('5ED','Fifth Edition',449,STR_TO_DATE('03.24.1997', GET_FORMAT(DATE,'USA')),'Core Set');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('6ED','Classic Sixth Edition',350,STR_TO_DATE('04.27.1999', GET_FORMAT(DATE,'USA')),'Core Set');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('7ED','Seventh Edition',350,STR_TO_DATE('04.02.2001', GET_FORMAT(DATE,'USA')),'Core Set');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('8ED','Eighth Edition',357,STR_TO_DATE('07.28.2003', GET_FORMAT(DATE,'USA')),'Core Set');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('9ED','Ninth Edition',359,STR_TO_DATE('07.29.2005', GET_FORMAT(DATE,'USA')),'Core Set');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('10E','Tenth Edition',383,STR_TO_DATE('07.13.2007', GET_FORMAT(DATE,'USA')),'Core Set');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('M10','Core Set 2010',249,STR_TO_DATE('07.17.2009', GET_FORMAT(DATE,'USA')),'Core Set');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('M11','Core Set 2011',249,STR_TO_DATE('07.16.2010', GET_FORMAT(DATE,'USA')),'Core Set');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('M12','Core Set 2012',249,STR_TO_DATE('07.15.2011', GET_FORMAT(DATE,'USA')),'Core Set');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('M13','Core Set 2013',249,STR_TO_DATE('07.13.2012', GET_FORMAT(DATE,'USA')),'Core Set');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('M14','Core Set 2014',249,STR_TO_DATE('07.19.2013', GET_FORMAT(DATE,'USA')),'Core Set');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('M15','Core Set 2015',249,STR_TO_DATE('07.18.2014', GET_FORMAT(DATE,'USA')),'Core Set');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('M19','Core Set 2019',280,STR_TO_DATE('07.13.2018', GET_FORMAT(DATE,'USA')),'Core Set');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DOM','Dominaria',269,STR_TO_DATE('04.27.2018', GET_FORMAT(DATE,'USA')),'Dominaria');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DD1','Duel Decks: Elves vs. Goblins',120,STR_TO_DATE('11.16.2007', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DD2','Duel Decks: Jace vs. Chandra',120,STR_TO_DATE('11.07.2008', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDC','Duel Decks: Divine vs. Demonic',120,STR_TO_DATE('04.10.2009', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDD','Duel Decks: Garruk vs. Liliana',120,STR_TO_DATE('10.30.2009', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDE','Duel Decks: Phyrexia vs. the Coalition',120,STR_TO_DATE('03.19.2010', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDF','Duel Decks: Elspeth vs. Tezzeret',120,STR_TO_DATE('09.03.2010', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDG','Duel Decks: Knights vs. Dragons',120,STR_TO_DATE('04.01.2011', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDH','Duel Decks: Ajani vs. Nicol Bolas',120,STR_TO_DATE('09.02.2011', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDI','Duel Decks: Venser vs. Koth',120,STR_TO_DATE('03.30.2012', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDJ','Duel Decks: Izzet vs. Golgari',120,STR_TO_DATE('09.07.2012', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDK','Duel Decks: Sorin vs. Tibalt',120,STR_TO_DATE('03.15.2013', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDL','Duel Decks: Heroes vs. Monsters',120,STR_TO_DATE('09.06.2013', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDM','Duel Decks: Jace vs. Vraska',120,STR_TO_DATE('03.14.2014', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDN','Duel Decks: Speed vs. Cunning',120,STR_TO_DATE('09.05.2014', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDO','Duel Decks: Elspeth vs. Kiora',120,STR_TO_DATE('02.27.2015', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDP','Duel Decks: Zendikar vs. Eldrazi',120,STR_TO_DATE('08.28.2015', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDQ','Duel Decks: Blessed vs. Cursed',120,STR_TO_DATE('02.26.2016', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDR','Duel Decks: Nissa vs. Ob Nixilis',120,STR_TO_DATE('09.02.2016', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDS','Duel Decks: Mind vs. Might',120,STR_TO_DATE('03.31.2017', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDT','Duel Decks: Merfolk vs. Goblins',120,STR_TO_DATE('11.10.2017', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DDU','Duel Decks: Elves vs. Inventors',120,STR_TO_DATE('04.06.2018', GET_FORMAT(DATE,'USA')),'Duel Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DVD','Duel Decks Anthology, Divine vs. Demonic',120, STR_TO_DATE('12.05.2014', GET_FORMAT(DATE,'USA')),'Duel Decks Reprint');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('EVG','Duel Decks Anthology, Elves vs. Goblins',120, STR_TO_DATE('12.05.2014', GET_FORMAT(DATE,'USA')),'Duel Decks Reprint');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('GVL','Duel Decks Anthology, Garruk vs. Liliana',120, STR_TO_DATE('12.05.2014', GET_FORMAT(DATE,'USA')),'Duel Decks Reprint');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('JVC','Duel Decks Anthology, Jace vs. Chandra',120, STR_TO_DATE('12.05.2014', GET_FORMAT(DATE,'USA')),'Duel Decks Reprint');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('FEM','Fallen Empires',102,STR_TO_DATE('11.01.1994', GET_FORMAT(DATE,'USA')),'Fallen Empires');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DRB','From the Vault: Dragons',15,STR_TO_DATE('08.29.2008', GET_FORMAT(DATE,'USA')),'From the Vault');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('V09','From the Vault: Exiled',15,STR_TO_DATE('08.28.2009', GET_FORMAT(DATE,'USA')),'From the Vault');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('V10','From the Vault: Relics',15,STR_TO_DATE('08.27.2010', GET_FORMAT(DATE,'USA')),'From the Vault');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('V11','From the Vault: Legends',15,STR_TO_DATE('08.26.2011', GET_FORMAT(DATE,'USA')),'From the Vault');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('V12','From the Vault: Realms',15,STR_TO_DATE('08.31.2012', GET_FORMAT(DATE,'USA')),'From the Vault');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('V13','From the Vault: Twenty',20,STR_TO_DATE('08.23.2013', GET_FORMAT(DATE,'USA')),'From the Vault');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('V14','From the Vault: Annihilation',15,STR_TO_DATE('08.22.2014', GET_FORMAT(DATE,'USA')),'From the Vault');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('V15','From the Vault: Angels',15,STR_TO_DATE('08.21.2015', GET_FORMAT(DATE,'USA')),'From the Vault');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('V16','From the Vault: Lore',15,STR_TO_DATE('08.19.2016', GET_FORMAT(DATE,'USA')),'From the Vault');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('V17','From the Vault: Transform',15,STR_TO_DATE('11.24.2017', GET_FORMAT(DATE,'USA')),'From the Vault');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('HML','Homelands',115,STR_TO_DATE('10.01.1995', GET_FORMAT(DATE,'USA')),'Homelands Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ICE','Ice Age',383,STR_TO_DATE('06.01.1995', GET_FORMAT(DATE,'USA')),'Ice Age Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ALL','Alliances',143,STR_TO_DATE('06.10.1996', GET_FORMAT(DATE,'USA')),'Ice Age Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('CSP','Coldsnap',155,STR_TO_DATE('07.21.2006', GET_FORMAT(DATE,'USA')),'Ice Age Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ISD','Innistrad',264,STR_TO_DATE('09.30.2011', GET_FORMAT(DATE,'USA')),'Innistrad Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DKA','Dark Ascension',158,STR_TO_DATE('02.03.2012', GET_FORMAT(DATE,'USA')),'Innistrad Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('AVR','Avacyn Restored',244,STR_TO_DATE('05.04.2012', GET_FORMAT(DATE,'USA')),'Innistrad Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('INV','Invasion',350,STR_TO_DATE('10.02.2000', GET_FORMAT(DATE,'USA')),'Invasion Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('PLS','Planeshift',143,STR_TO_DATE('02.05.2001', GET_FORMAT(DATE,'USA')),'Invasion Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('APC','Apocalypse',143,STR_TO_DATE('06.04.2001', GET_FORMAT(DATE,'USA')),'Invasion Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('XLN','Ixalan',279,STR_TO_DATE('09.29.2017', GET_FORMAT(DATE,'USA')),'Ixalan Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('RIX','Rivals of Ixalan',196,STR_TO_DATE('01.19.2018', GET_FORMAT(DATE,'USA')),'Ixalan Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('KLD','Kaladesh',264,STR_TO_DATE('09.30.2016', GET_FORMAT(DATE,'USA')),'Kaladesh Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('AER','Aether Revolt',184,STR_TO_DATE('01.20.2017', GET_FORMAT(DATE,'USA')),'Kaladesh Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('CHK','Champions of Kamigawa',306,STR_TO_DATE('10.01.2004', GET_FORMAT(DATE,'USA')),'Kamigawa Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('BOK','Betrayers of Kamigawa',165,STR_TO_DATE('02.04.2005', GET_FORMAT(DATE,'USA')),'Kamigawa Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('SOK','Saviors of Kamigawa',165,STR_TO_DATE('06.03.2005', GET_FORMAT(DATE,'USA')),'Kamigawa Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('KTK','Khans of Tarkir',269,STR_TO_DATE('09.26.2014', GET_FORMAT(DATE,'USA')),'Khans of Tarkir Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('FRF','Fate Reforged',185,STR_TO_DATE('01.23.2015', GET_FORMAT(DATE,'USA')),'Khans of Tarkir Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DTK','Dragons of Tarkir',264,STR_TO_DATE('03.27.2015', GET_FORMAT(DATE,'USA')),'Khans of Tarkir Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('LEG','Legends',310,STR_TO_DATE('06.01.1994', GET_FORMAT(DATE,'USA')),'Legends');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('LEA','Limited Edition Alpha',295,STR_TO_DATE('08.05.1993', GET_FORMAT(DATE,'USA')),'Limited');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('LEB','Limited Edition Beta',302,STR_TO_DATE('10.04.1993', GET_FORMAT(DATE,'USA')),'Limited');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('LRW','Lorwyn',301,STR_TO_DATE('10.12.2007', GET_FORMAT(DATE,'USA')),'Lorwyn Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('MOR','Morningtide',150,STR_TO_DATE('02.01.2008', GET_FORMAT(DATE,'USA')),'Lorwyn Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ME4','Masters Edition IV',245,STR_TO_DATE('01.10.2011', GET_FORMAT(DATE,'USA')),'Magic Online');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ME1','Masters Edition',195,STR_TO_DATE('09.10.2007', GET_FORMAT(DATE,'USA')),'Magic Online');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ME2','Masters Edition II',245,STR_TO_DATE('09.22.2008', GET_FORMAT(DATE,'USA')),'Magic Online');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ME3','Masters Edition III',245,STR_TO_DATE('09.07.2009', GET_FORMAT(DATE,'USA')),'Magic Online');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('TPR','Tempest Remastered',269,STR_TO_DATE('05.06.2015', GET_FORMAT(DATE,'USA')),'Magic Online');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('VMA','Vintage Masters',325,STR_TO_DATE('06.16.2014', GET_FORMAT(DATE,'USA')),'Magic Online');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ORI','Magic Origins',272,STR_TO_DATE('07.17.2015', GET_FORMAT(DATE,'USA')),'Magic Origins');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('MMQ','Mercadian Masques',350,STR_TO_DATE('10.04.1999', GET_FORMAT(DATE,'USA')),'Masques Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('NEM','Nemesis',143,STR_TO_DATE('02.14.2000', GET_FORMAT(DATE,'USA')),'Masques Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('PCY','Prophecy',143,STR_TO_DATE('06.05.2000', GET_FORMAT(DATE,'USA')),'Masques Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('MIR','Mirage',350,STR_TO_DATE('10.08.1996', GET_FORMAT(DATE,'USA')),'Mirage Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('VIS','Visions',167,STR_TO_DATE('02.03.1997', GET_FORMAT(DATE,'USA')),'Mirage Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('WTH','Weatherlight',167,STR_TO_DATE('06.09.1997', GET_FORMAT(DATE,'USA')),'Mirage Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('MRD','Mirrodin',306,STR_TO_DATE('10.02.2003', GET_FORMAT(DATE,'USA')),'Mirrodin Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DST','Darksteel',165,STR_TO_DATE('02.06.2004', GET_FORMAT(DATE,'USA')),'Mirrodin Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('5DN','Fifth Dawn',165,STR_TO_DATE('06.04.2004', GET_FORMAT(DATE,'USA')),'Mirrodin Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ODY','Odyssey',350,STR_TO_DATE('10.01.2001', GET_FORMAT(DATE,'USA')),'Odyssey Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('TOR','Torment',143,STR_TO_DATE('02.08.2002', GET_FORMAT(DATE,'USA')),'Odyssey Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('JUD','Judgment',143,STR_TO_DATE('05.27.2003', GET_FORMAT(DATE,'USA')),'Odyssey Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ONS','Onslaught',350,STR_TO_DATE('10.07.2002', GET_FORMAT(DATE,'USA')),'Onslaught Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('LGN','Legions',145,STR_TO_DATE('02.03.2003', GET_FORMAT(DATE,'USA')),'Onslaught Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('SCG','Scourge',143,STR_TO_DATE('05.26.2003', GET_FORMAT(DATE,'USA')),'Onslaught Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('POR','Portal',215,STR_TO_DATE('05.01.1997', GET_FORMAT(DATE,'USA')),'Portal');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('PO2','Portal Second Age',215,STR_TO_DATE('06.24.1998', GET_FORMAT(DATE,'USA')),'Portal');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('PTK','Portal Three Kingdoms',180,STR_TO_DATE('07.06.1999', GET_FORMAT(DATE,'USA')),'Portal');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('RNA','Ravnica Allegiance',259,STR_TO_DATE('01.25.2019', GET_FORMAT(DATE,'USA')),'Ravnica');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('GRN','Guilds of Ravnica',259,STR_TO_DATE('10.05.2018', GET_FORMAT(DATE,'USA')),'Ravnica');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('RAV','Ravnica: City of Guilds',306,STR_TO_DATE('10.07.2005', GET_FORMAT(DATE,'USA')),'Ravnica Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('GPT','Guildpact',165,STR_TO_DATE('02.03.2006', GET_FORMAT(DATE,'USA')),'Ravnica Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DIS','Dissension',180,STR_TO_DATE('05.05.2006', GET_FORMAT(DATE,'USA')),'Ravnica Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('WC99','World Champ Decks 1999',null,STR_TO_DATE('08.04.1999', GET_FORMAT(DATE,'USA')),'Ready-to-Play Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('WC00','World Champ Decks 2000',null,STR_TO_DATE('08.02.2000', GET_FORMAT(DATE,'USA')),'Ready-to-Play Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('WC01','World Champ Decks 2001',null,STR_TO_DATE('08.08.2001', GET_FORMAT(DATE,'USA')),'Ready-to-Play Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('WC02','World Champ Decks 2002',null,STR_TO_DATE('08.14.2002', GET_FORMAT(DATE,'USA')),'Ready-to-Play Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('WC03','World Champ Decks 2003',null,STR_TO_DATE('08.06.2003', GET_FORMAT(DATE,'USA')),'Ready-to-Play Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('WC04','World Champ Decks 2004',null,STR_TO_DATE('09.01.2004', GET_FORMAT(DATE,'USA')),'Ready-to-Play Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('H09','Premium Deck Series: Slivers',60,STR_TO_DATE('11.20.2009', GET_FORMAT(DATE,'USA')),'Ready-to-Play Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DPA','Duels of the Planeswalkers',null,STR_TO_DATE('06.04.2010', GET_FORMAT(DATE,'USA')),'Ready-to-Play Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('PD2','Premium Deck Series: Fire and Lightning',null,STR_TO_DATE('11.19.2010', GET_FORMAT(DATE,'USA')),'Ready-to-Play Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('TD2','Premium Deck Series: Graveborn',null,STR_TO_DATE('11.18.2011', GET_FORMAT(DATE,'USA')),'Ready-to-Play Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('MD1','Modern Event Deck',null,STR_TO_DATE('05.03.2014', GET_FORMAT(DATE,'USA')),'Ready-to-Play Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('Q01','Challenger Decks',81,STR_TO_DATE('04.06.2018', GET_FORMAT(DATE,'USA')),'Ready-to-Play Decks');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('CHR','Chronicles',116,STR_TO_DATE('07.01.1995', GET_FORMAT(DATE,'USA')),'Reprint Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('REN','Renaissance',null,STR_TO_DATE('08.01.1995', GET_FORMAT(DATE,'USA')),'Reprint Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ATH','Anthologies',null,STR_TO_DATE('11.01.1998', GET_FORMAT(DATE,'USA')),'Reprint Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('MMA','Modern Masters',229,STR_TO_DATE('06.07.2013', GET_FORMAT(DATE,'USA')),'Reprint Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('MM2','Modern Masters 2015 Edition',249,STR_TO_DATE('05.22.2015', GET_FORMAT(DATE,'USA')),'Reprint Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('EMA','Eternal Masters',249,STR_TO_DATE('06.10.2016', GET_FORMAT(DATE,'USA')),'Reprint Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('MM3','Modern Masters 2017 Edition',249,STR_TO_DATE('03.17.2017', GET_FORMAT(DATE,'USA')),'Reprint Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('IMA','Iconic Masters',249,STR_TO_DATE('11.17.2017', GET_FORMAT(DATE,'USA')),'Reprint Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('A25','Masters 25',249,STR_TO_DATE('03.16.2018', GET_FORMAT(DATE,'USA')),'Reprint Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('UMA','Ultimate Box Toppers',40,STR_TO_DATE('12.07.2018', GET_FORMAT(DATE,'USA')),'Reprint Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('UMA','Ultimate Masters',254,STR_TO_DATE('12.07.2018', GET_FORMAT(DATE,'USA')),'Reprint Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('RTR','Return to Ravnica',274,STR_TO_DATE('10.05.2012', GET_FORMAT(DATE,'USA')),'Return to Ravnica Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('GTC','Gatecrash',249,STR_TO_DATE('02.01.2013', GET_FORMAT(DATE,'USA')),'Return to Ravnica Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DGM','Dragon''s Maze',156,STR_TO_DATE('05.03.2013', GET_FORMAT(DATE,'USA')),'Return to Ravnica Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('SOM','Scars of Mirrodin',249,STR_TO_DATE('10.01.2010', GET_FORMAT(DATE,'USA')),'Scars of Mirrodin Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('MBS','Mirrodin Besieged',155,STR_TO_DATE('02.04.2011', GET_FORMAT(DATE,'USA')),'Scars of Mirrodin Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('NPH','New Phyrexia',175,STR_TO_DATE('05.13.2011', GET_FORMAT(DATE,'USA')),'Scars of Mirrodin Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('SHM','Shadowmoor',301,STR_TO_DATE('05.02.2008', GET_FORMAT(DATE,'USA')),'Shadowmoor Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('EVE','Eventide',180,STR_TO_DATE('07.25.2008', GET_FORMAT(DATE,'USA')),'Shadowmoor Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('SOI','Shadows over Innistrad',297,STR_TO_DATE('04.08.2016', GET_FORMAT(DATE,'USA')),'Shadows over Innistrad Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('EMN','Eldritch Moon',205,STR_TO_DATE('07.22.2016', GET_FORMAT(DATE,'USA')),'Shadows over Innistrad Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ALA','Shards of Alara',249,STR_TO_DATE('10.03.2008', GET_FORMAT(DATE,'USA')),'Shards of Alara Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ARB','Alara Reborn',145,STR_TO_DATE('04.30.2009', GET_FORMAT(DATE,'USA')),'Shards of Alara Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('CON','Conflux',145,STR_TO_DATE('02.06.2009', GET_FORMAT(DATE,'USA')),'Shards of Alara Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('SS1','Signature Spellbook: Jace',9,STR_TO_DATE('06.15.2018', GET_FORMAT(DATE,'USA')),'Signature Spellbook');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('S99','Starter 1999',173,STR_TO_DATE('07.12.1999', GET_FORMAT(DATE,'USA')),'Starter Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('S00','Starter 2000',173,STR_TO_DATE('04.24.2000', GET_FORMAT(DATE,'USA')),'Starter Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('TMP','Tempest',350,STR_TO_DATE('10.14.1997', GET_FORMAT(DATE,'USA')),'Tempest Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('STH','Stronghold',143,STR_TO_DATE('03.02.1998', GET_FORMAT(DATE,'USA')),'Tempest Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('EXO','Exodus',143,STR_TO_DATE('06.15.1998', GET_FORMAT(DATE,'USA')),'Tempest Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('DRK','The Dark',119,STR_TO_DATE('08.01.1994', GET_FORMAT(DATE,'USA')),'The Dark');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('THS','Theros',249,STR_TO_DATE('09.27.2013', GET_FORMAT(DATE,'USA')),'Theros Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('BNG','Born of the Gods',165,STR_TO_DATE('02.07.2014', GET_FORMAT(DATE,'USA')),'Theros Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('JOU','Journey into Nyx',165,STR_TO_DATE('05.02.2014', GET_FORMAT(DATE,'USA')),'Theros Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('TSP','Time Spiral',422,STR_TO_DATE('10.06.2006', GET_FORMAT(DATE,'USA')),'Time Spiral Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('PLC','Planar Chaos',165,STR_TO_DATE('02.02.2007', GET_FORMAT(DATE,'USA')),'Time Spiral Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('FUT','Future Sight',180,STR_TO_DATE('05.04.2007', GET_FORMAT(DATE,'USA')),'Time Spiral Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('BBD','Battlebond',254,STR_TO_DATE('06.08.2018', GET_FORMAT(DATE,'USA')),'Two-Headed Giant');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('UGL','Unglued',88,STR_TO_DATE('08.11.1998', GET_FORMAT(DATE,'USA')),'Un-Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('UNH','Unhinged',141,STR_TO_DATE('11.19.2004', GET_FORMAT(DATE,'USA')),'Un-Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('UST','Unstable',216,STR_TO_DATE('12.08.2017', GET_FORMAT(DATE,'USA')),'Un-Sets');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('USG','Urza''s Saga',350,STR_TO_DATE('10.12.1998', GET_FORMAT(DATE,'USA')),'Urza Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ULG','Urza''s Legacy',143,STR_TO_DATE('02.15.1999', GET_FORMAT(DATE,'USA')),'Urza Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('UDS','Urza''s Destiny',143,STR_TO_DATE('06.23.1999', GET_FORMAT(DATE,'USA')),'Urza Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ZEN','Zendikar',249,STR_TO_DATE('10.02.2009', GET_FORMAT(DATE,'USA')),'Zendikar Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('WWK','Worldwake',145,STR_TO_DATE('02.05.2010', GET_FORMAT(DATE,'USA')),'Zendikar Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('ROE','Rise of the Eldrazi',248,STR_TO_DATE('04.23.2010', GET_FORMAT(DATE,'USA')),'Zendikar Block');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('GS1','Global Series: Jiang Yanggu and Mu Yanling',120,STR_TO_DATE('06.22.2018', GET_FORMAT(DATE,'USA')),'');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('GNT','Game Night',300,STR_TO_DATE('11.16.2018', GET_FORMAT(DATE,'USA')),'Casual supplements');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('M19','Gift Pack M19',10,STR_TO_DATE('11.16.2018', GET_FORMAT(DATE,'USA')),'');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('GK1','Guild Kit',127,STR_TO_DATE('11.02.2018', GET_FORMAT(DATE,'USA')),'');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('MED','Guilds of Ravnica Mythic Edition',10,STR_TO_DATE('10.05.2018', GET_FORMAT(DATE,'USA')),'');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('MP2','Masterpiece Series: Amonkhet Invocations',null,STR_TO_DATE('04.28.2017', GET_FORMAT(DATE,'USA')),'');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('MPS','Masterpiece Series: Kaladesh Inventions',null,STR_TO_DATE('09.30.2016', GET_FORMAT(DATE,'USA')),'');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('TSB','Time Spiral "Timeshifted"',null,STR_TO_DATE('10.06.2006', GET_FORMAT(DATE,'USA')),'');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('???','Ugin''s Fate promos',26,STR_TO_DATE('01.17.2015', GET_FORMAT(DATE,'USA')),'');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('W16','Welcome Deck 2016',30,STR_TO_DATE('04.08.2016', GET_FORMAT(DATE,'USA')),'');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('W17','Welcome Deck 2017',30,STR_TO_DATE('04.15.2017', GET_FORMAT(DATE,'USA')),'');
INSERT INTO expansion (code, name, card_quantity, release_date, block) VALUES('EXP','Zendikar Expeditions',null,STR_TO_DATE('10.02.2015', GET_FORMAT(DATE,'USA')),'');
COMMIT;
